services:
  node-red:
    image: nodered/node-red:latest      # le indico al docker que imagen debe usar para generar el contenedor
    container_name: ProyectoFinal
    environment:
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "1880:1880"             # Mapeo el puerto 1880 interno del Node-red del contenedor con el puerto 1880 de mi maquina 
    volumes:
      - ./node_red_data:/data       # Mapeo el directoiro interno "/data" del conteneder con el directoiro de mi maquina "/node_red_data" 
    restart: unless-stopped